<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Controllers\AdministratorController;
use Illuminate\Support\Carbon;

class GradeDashboardController extends AdministratorController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Current year
        $year = Carbon::now()->year;

        // Department collection
        $departments = $this->department->all();

        // Grade collection
        $grades = $this->grade->orderBy('created_at', 'asc')->get();

        return view('dashboard.gradeclass.create-grade')
            ->withDepartments($departments)
            ->withGrades($grades)
            ->withYear($year);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Get the academic year only to construct grade unique code
        $academicDate = Carbon::parse($request['schoolyear_start']);
        $academicYear = $academicDate->year;

        $request['code'] = $academicYear . $request['department_code'] . $request['name'];

        $this->validate($request, [
            'code' => 'required|unique:grades',
            'name' => 'required|unique:grades,name,NULL,NULL,schoolyear_start,'. $academicYear,
            'schoolyear_start' => 'required',
            'schoolyear_end' => 'required',
            'department_code' => 'required'
        ],
        [
            'name.unique' => 'The grade in this department is already exist.',
            'code.unique' => 'The autogenerated code is not unique, the grade is already created and have the same academic year. Try create with the difference name.'
        ]);
        
        $input = $request->all();
        
        $this->grade->create($input);
        
        return redirect()->back()->with('success', 'New Grade has been created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}
